name: Release
on:
  create:
    tags:
      - v*

jobs:
  pyreleaser:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Docker release
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ismdeep/ustravel-info
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
          tags: "latest"